### ISSUE TITLE
不会检查邮箱是否可用

### ISSUE THREAD

**Issue by bocchi810** [qaqFei/BiliClear#11]
如果邮箱密码不对会显示图片中的错误或其他错误
![图片](https://github.com/user-attachments/assets/4205428f-489b-4628-96fa-18c933d77d4e)

**Comment by qaqFei** [comment]
已添加 (commit 34)[https://github.com/qaqFei/BiliClear/commit/5797dc72e1bd8d222eb1306d6dd97d1f5fa7512b]
