### ISSUE TITLE
优化匹配规则

### ISSUE THREAD

**Issue by Felixzhangmingzhe** [qaqFei/BiliClear#16]
![屏幕截图 2024-09-06 174022](https://github.com/user-attachments/assets/723149b2-c659-4428-983e-805436a58dd1)

如图，没有任何评论匹配规则

**Comment by qaqFei** [comment]
没辙, 找时间更新rules.txt, issue先开着

**Comment by CatalinaCharlotte** [comment]
有没有可能是不同的人推荐的视频不一样，推荐给你的视频里面这种评论比较少

**Comment by mxdabc** [comment]
目前想到的方案是接入词库匹配，看Owner是否同意 @qaqFei

**Comment by qaqFei** [comment]
看看效果咋样先吧
