### ISSUE TITLE
同一条视频会检测多次

### ISSUE THREAD

**Issue by bocchi810** [qaqFei/BiliClear#26]
如题

**Comment by mxdabc** [comment]
是同一个Bv/Av号会被循环使用么？
现在有个方案是使用MySQL数据库存储，但是要看Owner是否同意
或者是新建一个yml文件？
有待商讨

**Comment by qaqFei** [comment]
数据会越来越大, 没什么方法

**Comment by xiexiaozhua** [comment]
add gitee数据库如何？

**Comment by qaqFei** [comment]
我的方法是加一个json文件, 标注时间和avid, 超出时间的删掉

**Comment by qaqFei** [comment]
哪一种性能好就用哪一个

**Comment by xiexiaozhua** [comment]
我的想法是添加一个gitee库，每次打开从云端爬取数据，每次检测完导出一个txt的av号可以选择的提交进行审核

**Comment by xiexiaozhua** [comment]
这样可以做到同步

**Comment by qaqFei** [comment]
我也不知道用哪个(⊙ˍ⊙)

**Comment by xiexiaozhua** [comment]
gitee版本我写好了

**Comment by qaqFei** [comment]
pr还是...?

**Comment by qaqFei** [comment]
概率有点低吧  #51
