### ISSUE TITLE
QT gui?

### ISSUE THREAD

**Issue by xiexiaozhua** [qaqFei/BiliClear#30]
源码里有qtgui 实际没有释放？

**Comment by qaqFei** [comment]
qt是 @Felix3322 负责的

**Comment by Felix3322** [comment]
> 源码里有qtgui 实际没有释放？

gui是单独的文件

**Comment by Felix3322** [comment]
![image](https://github.com/user-attachments/assets/643e1dd3-9a0f-4736-9a9b-6e91007ce410)这段程序是qtgui代码 通过调用biliclear主程序里的函数实现识别，举报等功能 gui程序只提供界面
