### ISSUE TITLE
需求:代理服务器（仅限Openai API使用）

### ISSUE THREAD

**Issue by bocchi810** [qaqFei/BiliClear#31]
如果支持socks5和http等代理协议就可以了

**Comment by bocchi810** [comment]
当然，后续如果想支持Copilot或者Gemini等国外AI，也建议给它们代理支持

**Comment by qaqFei** [comment]
在config.json的gpt_apibase里

**Comment by bocchi810** [comment]
> 在config.json的gpt_apibase里

那似乎只支持反代服务器（镜像站），我需要的是正代服务器

**Comment by qaqFei** [comment]
可以了, config.json的gpt_proxy, 默认为null
