### ISSUE TITLE
求解答

### ISSUE THREAD

**Issue by 114514fuckyou** [qaqFei/BiliClear#34]
![捕获](https://github.com/user-attachments/assets/603ebfaf-1ca7-4435-ac94-db76b0acaeb2)
无法启动

**Comment by qaqFei** [comment]
smtp服务器选择其他有ssl的端口, 这里可以修改config.json也可以删掉重配

**Comment by Felix3322** [comment]
我代码还没适配新文件结构呢 先不要发行我的

**Comment by qaqFei** [comment]
这是release0.2, 0.3是2个都编译 @Felix3322 不是源码

**Comment by qaqFei** [comment]
加了提示了
