### ISSUE TITLE
配合人脸识别，添加检测二维码的功能

### ISSUE THREAD

**Issue by bocchi810** [qaqFei/BiliClear#35]
有些片哥会在评论区或者动态放二维码并且配”V扫“之类的字眼，所以我建议添加一个配合人脸识别的检测二维码功能

**Comment by bocchi810** [comment]
例如
![屏幕截图 2024-09-07 214415](https://github.com/user-attachments/assets/ae109c30-d608-4179-b072-39481d8233d7)

**Comment by Felix3322** [comment]
目前只能识别头像中的人脸，尽快更新

**Comment by qaqFei** [comment]
行

**Comment by qaqFei** [comment]
已更新
