### ISSUE TITLE
B站举报api调用失败

### ISSUE THREAD

**Issue by Jason-crap** [qaqFei/BiliClear#39]
![D5B7756D-8DD0-458B-9833-758BB0DFC1FF](https://github.com/user-attachments/assets/79345c95-636e-48cd-b994-ff6b49300ae7)

**Comment by Jason-crap** [comment]
如图

**Comment by Felix3322** [comment]
删掉config试试？

**Comment by Jason-crap** [comment]
试过了，还是一样

**Comment by Felix3322** [comment]
我查一下

**Comment by qaqFei** [comment]
api文档没写, 我也不知道
[click](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/comment/action.md#%E4%B8%BE%E6%8A%A5%E8%AF%84%E8%AE%BA)

**Comment by CatalinaCharlotte** [comment]
同样遇到这个问题，盲猜是举报次数累计多了？

**Comment by CatalinaCharlotte** [comment]
今天早上测试发现仍然没有解除此状态

**Comment by Felix3322** [comment]
你可以尝试更换账号，尝试添加更多调试信息 需要帮助的话可以找我

**Comment by ELDment** [comment]
> api文档没写, 我也不知道 [click](https://github.com/SocialSisterYi/bilibili-API-collect/blob/master/docs/comment/action.md#%E4%B8%BE%E6%8A%A5%E8%AF%84%E8%AE%BA)

当同一接口在短时间内被**同一用户/IP/UA**多次请求或异常时, 会触发风控, 如接口返回 `code` 为 `-352` 即 `风控校验失败`
[详见](https://github.com/SocialSisterYi/bilibili-API-collect/blob/60a0c5d1a2f44fe61335da04571305fa7727a968/docs/misc/errcode.md?plain=1#L34)

**Comment by qaqFei** [comment]
#51
