### ISSUE TITLE
规则"v" in text and "扫" in text误报

### ISSUE THREAD

**Issue by FrzMtrsprt** [qaqFei/BiliClear#41]
### 误报视频链接
https://www.bilibili.com/video/av113090414772923/
### 匹配规则
```python
"V" in text and "扫" in text or "v" in text and "扫" in text
```
### 误报评论
> 感谢林哥提供比赛的机会，我是秒速5毫米的开发。我的项目其实是想降低扫描软件的使用难度，提升扫描效率。「如果手机的速度不超过秒速 5 毫米，其实是可以清楚读到世界上所有信息的。」
> 项目出发点是我自己动了手术，没体力看药瓶上面买圆柱形的说明书，所以开发了这样的一个工具。这个时候也发现了很多延伸用途，例如电子产品说明书容易遗失，药品说明不容易理解，等等……
> 
> 这次比赛有很多感触吧，回头写个长文介绍一下自己的项目。项目链接：
> 
> - https://github.com/Chivier/5mmps
> - https://github.com/Chivier/Nerif
> 
> 不过因为太懒还没更新文档，周末加个班补上。

感觉这种对单个拉丁字母的匹配很容易会被网址、英文单词之类的评论误撞。

![{E9FC5C6B-0F3A-4A2F-92A7-BC2D76003D4C}](https://github.com/user-attachments/assets/f635a09e-06b7-4233-b633-9bd7c0fed3d5)

**Comment by Felix3322** [comment]
您可以提出更好的规则

**Comment by FrzMtrsprt** [comment]
我这边没有这个规则对应的正样本，所以我也不是很清楚该匹配什么样的特征

**Comment by qaqFei** [comment]
规则已删除
