### ISSUE TITLE
可以对小孩子乱打的评论进行额外匹配

### ISSUE THREAD

**Issue by xiaolan610** [qaqFei/BiliClear#49]
可以参考：[死妈爷爷](https://bilibili.com/video/BV1qS411w7nC)下的部分评论

**Comment by bocchi810** [comment]
这样不符合初衷了，你还不如说连键政圈的关键词也匹配上算了

**Comment by Felix3322** [comment]
> 这样不符合初衷了，你还不如说连键政圈的关键词也匹配上算了

说实话现在已经不只是检测擦边，色情内容了

**Comment by Felix3322** [comment]
广告什么的都检测了，虚假募捐也检测了
![image](https://github.com/user-attachments/assets/c55b7106-a5ce-4158-87b8-a20352d26c6e)

**Comment by bocchi810** [comment]
> 广告什么的都检测了，虚假募捐也检测了
> ![image](https://github.com/user-attachments/assets/c55b7106-a5ce-4158-87b8-a20352d26c6e)
> 

这个还算初衷之内

**Comment by Felix3322** [comment]
> 可以参考：[死妈爷爷](https://bilibili.com/video/BV1qS411w7nC)下的部分评论

太难判断了 gpt也没那么聪明
