### ISSUE TITLE
自己看

### ISSUE THREAD

**Issue by xiexiaozhua** [qaqFei/BiliClear#50]
lv.2和人脸检测, 结果: True

误判评论: '@CKKWSR'
正常@语句，误判pass
lv.2和人脸检测, 结果: False
lv.2和人脸检测, 结果: True

误判评论: '@ぅ不丢 @S幽羽X @我是阿美的狗 @希米露的妍妍子 @雨云a @愉快的一只猪 @瓷家的小粤兔子 @以此身捍卫中华'
正常@语句，误判pass
lv.2和人脸检测, 结果: True

误判评论: '@TA棠安'
正常@语句，误判pass
lv.2和人脸检测, 结果: True

误判评论: '@大帅比Pro_Max'
正常@语句，误判pass
开始检查视频: av113069392922533, 现在时间: 2024-09-08 15:12:12
lv.2和人脸检测, 结果: False
lv.2和人脸检测, 结果: True

误判评论: '@百合什么的最好了a'
正常@语句，误判pass
lv.2和人脸检测, 结果: True

误判评论: '@不只会浪费绷带'
正常@语句，误判pass

**Comment by qaqFei** [comment]
下次检测一下用户名吧

**Comment by xiexiaozhua** [comment]
> 下次检测一下用户名吧
可以的，你自己写一个用户名检测，我这只是检测

**Comment by qaqFei** [comment]
#51
