### ISSUE TITLE
项目`Owner`要上学, 所以`周一~周五` issue和pr不会及时处理

### ISSUE THREAD

**Issue by qaqFei** [qaqFei/BiliClear#51]

**Comment by qaqFei** [comment]
我觉得代码风格要出大问题... 周六解决

**Comment by IsCycleBai** [comment]
> 我觉得代码风格要出大问题... 周六解决

代码风格先别管，我建议先加个 Commit 规范

**Comment by qaqFei** [comment]
下周末 (2024.9.21 & 2024.9.22) 将会将现有代码整理并实现`checkUser`函数的调用,
会尽数处理issue和pr,
随后发布release-0.3, 项目将会停止维护

@Felix3322 @wling-art @mxdabc @molanp @JackHaozhu @bocchi810 @ELDment @zangmeng1 @beluga383 @xjh2009 @jjssszzr @xiexiaozhua @FrzMtrsprt @jinyiwei2012 
#81 #71 #66 #64 #62 #50 #39 #38 #26 #83

**Comment by qaqFei** [comment]
> 这就停止维护了？

阿B不见起色, 放任这种现象, 所以也不打算维护了

**Comment by zangmeng1** [comment]
说句难听的，就该早点开始脚本对轰，等所有人都开始了解这个问题，b站就开始管了（）

**Comment by IsCycleBai** [comment]
> 说句难听的，就该早点开始脚本对轰，等所有人都开始了解这个问题，b站就开始管了（）

要我说，感觉自己搭各视频平台比较有可能（）

**Comment by qaqFei** [comment]
> 说句难听的，就该早点开始脚本对轰，等所有人都开始了解这个问题，b站就开始管了（）

那还不如biliclear里面用一个线程dos攻击呢......

**Comment by IsCycleBai** [comment]
> > 说句难听的，就该早点开始脚本对轰，等所有人都开始了解这个问题，b站就开始管了（）
> 
> 那还不如biliclear里面用一个线程dos攻击呢......

你这样那我可就……
震惊！知名项目被曝后门？经典攻击手段重演！安全何在！

**Comment by molanp** [comment]
#62 等待代码整理完成后我会fork出来尝试实现

u1s1应该接入云审查服务(比如阿里百度之类的)，让用户自己承担成本

等几天看看吧

**Comment by qaqFei** [comment]
> > > 说句难听的，就该早点开始脚本对轰，等所有人都开始了解这个问题，b站就开始管了（）
> > 
> > 
> > 那还不如biliclear里面用一个线程dos攻击呢......
> 
> 你这样那我可就…… 震惊！知名项目被曝后门？经典攻击手段重演！安全何在！

![doge](https://i0.hdslb.com/bfs/emote/3087d273a78ccaff4bb1e9972e2ba2a7583c9f11.png)

**Comment by zangmeng1** [comment]
> > 说句难听的，就该早点开始脚本对轰，等所有人都开始了解这个问题，b站就开始管了（）
> 
> 那还不如biliclear里面用一个线程dos攻击呢……

所以我提交了关于青龙面板的更新，他们24小时发，用户24小时删，等b站全是脚本了没人了也就该出手了。我在学校的几个交流社区就这么玩的，管理员不可能不出面。（）

**Comment by molanp** [comment]
> > #62 等待代码整理完成后我会fork出来尝试实现
> > u1s1应该接入云审查服务(比如阿里百度之类的)，让用户自己承担成本
> > 等几天看看吧
> 
> u1s1 我觉得本地跑个分类模型比这个现实

分类模型会出来一堆issues，大部分人不会配推理环境

**Comment by IsCycleBai** [comment]
> > > #62 等待代码整理完成后我会fork出来尝试实现
> > > u1s1应该接入云审查服务(比如阿里百度之类的)，让用户自己承担成本
> > > 等几天看看吧
> > 
> > 
> > u1s1 我觉得本地跑个分类模型比这个现实
> 
> 分类模型会出来一堆issues，大部分人不会配推理环境

咋突然炸出来这么多人（）各位都时刻盯邮箱的吗

我感觉 PyTorch 还挺简单的，直接 clone 下来应该不至于不会用……吧？

**Comment by molanp** [comment]
> > > > #62 等待代码整理完成后我会fork出来尝试实现
> > > > u1s1应该接入云审查服务(比如阿里百度之类的)，让用户自己承担成本
> > > > 等几天看看吧
> > > 
> > > 
> > > u1s1 我觉得本地跑个分类模型比这个现实
> > 
> > 
> > 分类模型会出来一堆issues，大部分人不会配推理环境
> 
> 咋突然炸出来这么多人（）各位都时刻盯邮箱的吗
> 
> 我感觉 PyTorch 还挺简单的，直接 clone 下来应该不至于不会用……吧？

如图，这是我在管理的一个仓库，用户自己配环境会遇到各种各样想不到的问题
![屏幕截图 2024-09-17 212425](https://github.com/user-attachments/assets/d1d1ea13-889c-4434-9893-725d68eccd12)

**Comment by IsCycleBai** [comment]
> > > > > #62 等待代码整理完成后我会fork出来尝试实现
> > > > > u1s1应该接入云审查服务(比如阿里百度之类的)，让用户自己承担成本
> > > > > 等几天看看吧
> > > > 
> > > > 
> > > > u1s1 我觉得本地跑个分类模型比这个现实
> > > 
> > > 
> > > 分类模型会出来一堆issues，大部分人不会配推理环境
> > 
> > 
> > 咋突然炸出来这么多人（）各位都时刻盯邮箱的吗
> > 我感觉 PyTorch 还挺简单的，直接 clone 下来应该不至于不会用……吧？
> 
> 如图，这是我在管理的一个仓库，用户自己配环境会遇到各种各样想不到的问题 ![屏幕截图 2024-09-17 212425](https://private-user-images.githubusercontent.com/104612722/368184316-d1d1ea13-889c-4434-9893-725d68eccd12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY1Nzk4NzcsIm5iZiI6MTcyNjU3OTU3NywicGF0aCI6Ii8xMDQ2MTI3MjIvMzY4MTg0MzE2LWQxZDFlYTEzLTg4OWMtNDQzNC05ODkzLTcyNWQ2OGVjY2QxMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxN1QxMzI2MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZmU0YTY4NzhmMzliODE3ZTQ0OWM2YWU1OTFmNGNlZDUyZTI5Mjg4M2NiNjIzNDg2ZWNhM2YwZjZmMjBiODEzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.1KSMZRz0RmOJfDI2dxeW4G1jESw6eMJ_NrNT9CkJJgU)

这种我会选择在 README 里放 FAQ 和提问的智慧（）

**Comment by molanp** [comment]
> 这种我会选择在 README 里放 FAQ 和提问的智慧（）

相信我，不会有几个人看的，我甚至设置了issues双语模板，提交的时候都不规范，还有随便选的

**Comment by IsCycleBai** [comment]
> > 这种我会选择在 README 里放 FAQ 和提问的智慧（）
> 
> 相信我，不会有几个人看的，我甚至设置了issues双语模板，提交的时候都不规范，还有随便选的

你是否在搜索：
- Github Issue 表单
- 自动 CI, 不符合格式自动以 Not planned 关闭

**Comment by molanp** [comment]
相关仓库[BiliClearX](https://github.com/molanp/BiliClearX)

近期不会更新，还有什么功能请求提一下issues，会来一起做

**Comment by IsCycleBai** [comment]
相关仓库 [BiliCleaner](https://github.com/IsCycleBai/BiliCleaner)
积极维护。

@qaqFei 建议添加一些还在维护的 Fork 列表。

**Comment by beluga383** [comment]
没事，我c＃会重写这个代码，用.net

**Comment by IsCycleBai** [comment]
> 没事，我c＃会重写这个代码，用.net

BiliCleaner 会用 Rust 重写

**Comment by qaqFei** [comment]
`ヾ(≧▽≦*)o` 加油

**Comment by qaqFei** [comment]
qt_gui将会被抽离main分支, 存放在另一分支内 @Felix3322

**Comment by ELDment** [comment]
> 没事，我c＃会重写这个代码，用.net

net core?

**Comment by qaqFei** [comment]
`BiliClear` 停止维护

@Felix3322 @wling-art @mxdabc @molanp @JackHaozhu @bocchi810 @ELDment @zangmeng1 @beluga383 @xjh2009 @jjssszzr @xiexiaozhua @FrzMtrsprt @jinyiwei2012

**Comment by wling-art** [comment]
实在不行就找几个信任的Contributors继续维护项目吧

**Comment by ELDment** [comment]
> 实在不行就找几个信任的Contributors继续维护项目吧

没什么意义，这个就成品而言已经成熟了。
