### ISSUE TITLE
webui启动失败

### ISSUE THREAD

**Issue by jinyiwei2012** [qaqFei/BiliClear#71]
Traceback (most recent call last):
  File "C:\BiliClear\biliclear_gui_webui.py", line 228, in <module>
    webdpr = root.run_js_code("window.devicePixelRatio;")
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\BiliClear\web_canvas.py", line 213, in run_js_code
    return self._web.evaluate_js(code)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\hyh_1\AppData\Roaming\Python\Python312\site-packages\webview\window.py", line 45, in wrapper
    raise WebViewException('Main window failed to start')
webview.errors.WebViewException: Main window failed to start

**Comment by qaqFei** [comment]
神奇, 能给出更详细的描述吗

**Comment by qaqFei** [comment]
或者可能的复现方法

**Comment by jinyiwei2012** [comment]
![image](https://github.com/user-attachments/assets/67aa8497-7e6f-4713-9c74-639589fab81f)

https://github.com/user-attachments/assets/4cdc4e33-066f-41d8-9700-c8a0a91eda22

**Comment by jinyiwei2012** [comment]
主程序和QTgui都没问题

**Comment by qaqFei** [comment]
这应该是webview的问题了, 不在本项目维护的范畴内
(pywebview)[https://github.com/r0x0r/pywebview]
可以到这里提issue

**Comment by jinyiwei2012** [comment]
但是编译好的webui又可以用

**Comment by jinyiwei2012** [comment]
神奇的现象出现了，我重新建了个虚拟环境，python=3.12.4 安了依赖又可以运行了，之前的也是3.12.4

**Comment by Felix3322** [comment]
qt不香吗

**Comment by qaqFei** [comment]
...

> qt不香吗

**Comment by Felix3322** [comment]
> ...
> 
> > qt不香吗

...

**Comment by qaqFei** [comment]
> > ...
> > > qt不香吗
> 
> ...

...

**Comment by Felix3322** [comment]
> > > ...
> 
> > > > qt不香吗
> 
> > 
> 
> > ...
> 
> 
> 
> ...

...

**Comment by qaqFei** [comment]
太神奇了, 无法复现
