### ISSUE TITLE
疑似被风控未识别？

### ISSUE THREAD

**Issue by hyb-oyqq** [qaqFei/BiliClear#84]
脚本报错，但gui界面仍显示B站API风控中：false
`b站举报评论API调用失败, 返回体： {'code': -352, 'message': '-352', 'ttl': 1}`
![QQ20240919-021421](https://github.com/user-attachments/assets/dc34e114-bb34-4fb8-8f4b-21257d6d6570)

使用同账号同网络环境手机客户端手动举报会弹出验证码验证，并收到举报频繁的提醒
<details>
  <summary>图片过大，故折叠</summary>

![Screenshot_2024-09-19-02-10-33-200_tv danmaku bil](https://github.com/user-attachments/assets/e96d438f-bcd3-493a-b6b8-5c75bf08ce04)
![Screenshot_2024-09-19-02-10-40-716_tv danmaku bil](https://github.com/user-attachments/assets/2da8c2fc-cfcd-4d54-b5df-9b3d99af7a61)

</details>

**Comment by hyb-oyqq** [comment]
已在https://github.com/qaqFei/BiliClear/issues/51#issuecomment-2355715558看见对应issues，close

**Comment by qaqFei** [comment]
已修复
![微信截图_20240919184104](https://github.com/user-attachments/assets/76604140-f009-4381-a08c-1697e5cb8780)
